---
name: Release Containers
on:
  # https://github.com/actions/runner/issues/1007
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release-containers:
    name: Build and Push container - ${{ matrix.containers.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        containers:
          - name: badrobot
            file: ./Dockerfile
            suffix: ""
          - name: badrobot alpine
            file: ./Dockerfile.alpine
            suffix: -alpine

    steps:
      - name: Cache container layers
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}${{ matrix.containers.suffix }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}${{ matrix.containers.suffix }}-buildx-

      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          persist-credentials: false

      - name: Generate container tags and labels
        id: docker_meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5.10.0
        with:
          images: controlplane/badrobot
          tags: |
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}
          flavor: |
            latest=${{ matrix.containers.suffix == '' }}
            suffix=${{ matrix.containers.suffix }}
          labels: |
            org.opencontainers.image.vendor=controlplane

      - name: Login to Docker Hub Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3.6.0
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.CR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Build container and push tags
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          file: ${{ matrix.containers.file }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: mode=max,type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            VERSION=${{ fromJSON(steps.docker_meta.outputs.json).labels['org.opencontainers.image.version'] }}
            COMMIT=${{ fromJSON(steps.docker_meta.outputs.json).labels['org.opencontainers.image.revision'] }}
