---
name: Testing - Acceptance
permissions: {}
# Split until path filtering for jobs added
# https://github.community/t/path-filtering-for-jobs-and-steps/16447
on:
  push:
    branches: [master]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "**.bash"
      - "**.bats"
  pull_request:
    branches: [master]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
      - "**.bash"
      - "**.bats"

jobs:
  acceptance:
    name: Bats acceptance tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          persist-credentials: false
          # needed for bats tests
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        id: go
        with:
          go-version-file: go.mod

      - name: Run bats acceptance tests
        run: |
          make build test-acceptance
